# Generated by Django 6.0 on 2026-04-25 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0022_set_submit_role_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowconfig',
            name='phase',
            field=models.CharField(choices=[('APPLICATION', '立项'), ('MID_TERM', '中期'), ('CLOSURE', '结题'), ('BUDGET', '经费'), ('CHANGE', '异动')], max_length=20, verbose_name='流程阶段'),
        ),
    ]
