# Generated by Django 4.2.7 on 2025-10-31 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_no', models.CharField(blank=True, max_length=50, unique=True, verbose_name='项目编号')),
                ('title', models.CharField(max_length=200, verbose_name='项目名称')),
                ('description', models.TextField(blank=True, verbose_name='项目简介')),
                ('level', models.CharField(choices=[('NATIONAL', '国家级'), ('PROVINCIAL', '省级'), ('SCHOOL', '校级')], default='SCHOOL', max_length=20, verbose_name='项目级别')),
                ('category', models.CharField(choices=[('INNOVATION_TRAINING', '创新训练项目'), ('ENTREPRENEURSHIP_TRAINING', '创业训练项目'), ('ENTREPRENEURSHIP_PRACTICE', '创业实践项目')], default='INNOVATION_TRAINING', max_length=50, verbose_name='项目类别')),
                ('leader_student_id', models.CharField(blank=True, default='', max_length=20, verbose_name='项目负责人学号')),
                ('leader_contact', models.CharField(blank=True, default='', max_length=50, verbose_name='负责人联系方式')),
                ('leader_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='负责人联系邮箱')),
                ('is_key_field', models.BooleanField(default=False, verbose_name='重点领域项目')),
                ('college', models.CharField(blank=True, default='', max_length=100, verbose_name='学院')),
                ('major_code', models.CharField(blank=True, default='', max_length=50, verbose_name='项目所属专业代码')),
                ('self_funding', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='项目自筹（元）')),
                ('category_description', models.TextField(blank=True, default='', verbose_name='立项类别描述')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='项目经费')),
                ('research_content', models.TextField(blank=True, verbose_name='研究内容')),
                ('research_plan', models.TextField(blank=True, verbose_name='研究方案')),
                ('expected_results', models.TextField(blank=True, verbose_name='预期成果')),
                ('innovation_points', models.TextField(blank=True, verbose_name='创新点')),
                ('proposal_file', models.FileField(blank=True, null=True, upload_to='proposals/', verbose_name='申报书')),
                ('attachment_file', models.FileField(blank=True, null=True, upload_to='attachments/', verbose_name='上传文件')),
                ('final_report', models.FileField(blank=True, null=True, upload_to='final_reports/', verbose_name='结题报告')),
                ('achievement_file', models.FileField(blank=True, null=True, upload_to='achievements/', verbose_name='成果材料')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('SUBMITTED', '已提交'), ('LEVEL2_REVIEWING', '二级审核中'), ('LEVEL2_APPROVED', '二级审核通过'), ('LEVEL2_REJECTED', '二级审核不通过'), ('LEVEL1_REVIEWING', '一级审核中'), ('LEVEL1_APPROVED', '一级审核通过'), ('LEVEL1_REJECTED', '一级审核不通过'), ('IN_PROGRESS', '进行中'), ('CLOSURE_DRAFT', '结题草稿'), ('CLOSURE_SUBMITTED', '结题已提交'), ('CLOSURE_LEVEL2_REVIEWING', '结题二级审核中'), ('CLOSURE_LEVEL2_APPROVED', '结题二级审核通过'), ('CLOSURE_LEVEL2_REJECTED', '结题二级审核不通过'), ('CLOSURE_LEVEL1_REVIEWING', '结题一级审核中'), ('CLOSURE_LEVEL1_APPROVED', '结题一级审核通过'), ('CLOSURE_LEVEL1_REJECTED', '结题一级审核不通过'), ('COMPLETED', '已完成'), ('CLOSED', '已结题')], default='DRAFT', max_length=30, verbose_name='项目状态')),
                ('ranking', models.IntegerField(blank=True, null=True, verbose_name='项目排名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('closure_applied_at', models.DateTimeField(blank=True, null=True, verbose_name='结题申请时间')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='led_projects', to=settings.AUTH_USER_MODEL, verbose_name='项目负责人')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='进度标题')),
                ('content', models.TextField(verbose_name='进度内容')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='progress/', verbose_name='附件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目进度',
                'verbose_name_plural': '项目进度',
                'db_table': 'project_progress',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('LEADER', '负责人'), ('MEMBER', '成员')], default='MEMBER', max_length=20, verbose_name='角色')),
                ('student_id', models.CharField(blank=True, max_length=20, verbose_name='学号')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='成员姓名')),
                ('join_date', models.DateField(auto_now_add=True, verbose_name='加入日期')),
                ('contribution', models.TextField(blank=True, verbose_name='贡献说明')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='成员')),
            ],
            options={
                'verbose_name': '项目成员',
                'verbose_name_plural': '项目成员',
                'db_table': 'project_members',
                'unique_together': {('project', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ProjectAdvisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='指导教师姓名')),
                ('title', models.CharField(max_length=50, verbose_name='指导教师职称')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='指导教师单位')),
                ('contact', models.CharField(blank=True, max_length=50, verbose_name='指导教师联系方式')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='指导教师邮箱')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisors', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目指导教师',
                'verbose_name_plural': '项目指导教师',
                'db_table': 'project_advisors',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(related_name='joined_projects', through='projects.ProjectMember', to=settings.AUTH_USER_MODEL, verbose_name='项目成员'),
        ),
        migrations.CreateModel(
            name='ProjectAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('PAPER', '论文'), ('PATENT', '专利'), ('SOFTWARE_COPYRIGHT', '软件著作权'), ('COMPETITION_AWARD', '竞赛奖项'), ('OTHER', '其他')], max_length=30, verbose_name='成果类型')),
                ('title', models.CharField(max_length=200, verbose_name='成果名称')),
                ('description', models.TextField(verbose_name='成果描述')),
                ('authors', models.CharField(blank=True, max_length=200, verbose_name='作者')),
                ('journal', models.CharField(blank=True, max_length=200, verbose_name='期刊/会议名称')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='发表日期')),
                ('doi', models.CharField(blank=True, max_length=100, verbose_name='DOI')),
                ('patent_no', models.CharField(blank=True, max_length=100, verbose_name='专利号')),
                ('patent_type', models.CharField(blank=True, max_length=50, verbose_name='专利类型')),
                ('applicant', models.CharField(blank=True, max_length=200, verbose_name='申请人')),
                ('copyright_no', models.CharField(blank=True, max_length=100, verbose_name='登记号')),
                ('copyright_owner', models.CharField(blank=True, max_length=200, verbose_name='著作权人')),
                ('competition_name', models.CharField(blank=True, max_length=200, verbose_name='竞赛名称')),
                ('award_level', models.CharField(blank=True, max_length=50, verbose_name='获奖等级')),
                ('award_date', models.DateField(blank=True, null=True, verbose_name='获奖日期')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='achievements/', verbose_name='成果附件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目成果',
                'verbose_name_plural': '项目成果',
                'db_table': 'project_achievements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'achievement_type'], name='project_ach_project_43f9d6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_no'], name='projects_project_b2c64d_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='projects_status_6303d7_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['college'], name='projects_college_4ff92e_idx'),
        ),
    ]
