# Generated by Django 4.2.7 on 2025-12-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='source',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='项目来源'),
        ),
    ]
