# Generated by Django 4.2.7 on 2025-12-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('DRAFT', '草稿'), ('SUBMITTED', '已提交'), ('IN_PROGRESS', '进行中'), ('CLOSURE_DRAFT', '结题草稿'), ('CLOSURE_SUBMITTED', '结题已提交'), ('CLOSURE_LEVEL2_REVIEWING', '结题二级审核中'), ('CLOSURE_LEVEL2_APPROVED', '结题二级审核通过'), ('CLOSURE_LEVEL2_REJECTED', '结题二级审核不通过'), ('CLOSURE_LEVEL1_REVIEWING', '结题一级审核中'), ('CLOSURE_LEVEL1_APPROVED', '结题一级审核通过'), ('CLOSURE_LEVEL1_REJECTED', '结题一级审核不通过'), ('COMPLETED', '已完成'), ('CLOSED', '已结题')], default='DRAFT', max_length=30, verbose_name='项目状态'),
        ),
    ]
