# Generated by Codex on 2026-04-25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dictionaries", "0004_seed_project_level_items"),
        ("projects", "0035_remove_change_request_extension_termination"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="final_budget",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="最终立项经费",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="final_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projects_final_level",
                to="dictionaries.dictionaryitem",
                verbose_name="最终立项级别",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="是否删除"),
        ),
        migrations.AddField(
            model_name="project",
            name="publish_status",
            field=models.CharField(
                choices=[
                    ("NOT_READY", "未进入发布"),
                    ("RECOMMENDED", "学院已推荐"),
                    ("CONFIRMED", "学校已确认"),
                    ("PUBLISHED", "已发布"),
                ],
                default="NOT_READY",
                max_length=20,
                verbose_name="发布状态",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="发布时间"),
        ),
        migrations.AddField(
            model_name="project",
            name="published_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="published_projects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="发布人",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="recommendation_comment",
            field=models.TextField(blank=True, verbose_name="学院推荐意见"),
        ),
        migrations.AddField(
            model_name="project",
            name="recommendation_rank",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="学院推荐排序"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="recommended_budget",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="学院推荐经费",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="recommended_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projects_recommended_level",
                to="dictionaries.dictionaryitem",
                verbose_name="学院推荐级别",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["publish_status"], name="projects_publish_63598c_idx"
            ),
        ),
    ]
