# Generated by Codex on 2026-04-25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="资料名称")),
                ("description", models.TextField(blank=True, verbose_name="资料说明")),
                ("category", models.CharField(blank=True, max_length=50, verbose_name="资料分类")),
                ("target_roles", models.JSONField(blank=True, default=list, verbose_name="可见角色")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to="materials/",
                        verbose_name="资料文件",
                    ),
                ),
                ("external_url", models.URLField(blank=True, verbose_name="外部链接")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                ("download_count", models.PositiveIntegerField(default=0, verbose_name="下载次数")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_platform_materials",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "资料下载",
                "verbose_name_plural": "资料下载",
                "db_table": "platform_materials",
                "ordering": ["category", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlatformNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="公告标题")),
                ("content", models.TextField(verbose_name="公告内容")),
                ("target_roles", models.JSONField(blank=True, default=list, verbose_name="可见角色")),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "草稿"), ("PUBLISHED", "已发布")],
                        default="PUBLISHED",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("is_pinned", models.BooleanField(default=False, verbose_name="是否置顶")),
                ("published_at", models.DateTimeField(blank=True, null=True, verbose_name="发布时间")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_platform_notices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "平台公告",
                "verbose_name_plural": "平台公告",
                "db_table": "platform_notices",
                "ordering": ["-is_pinned", "-published_at", "-created_at"],
            },
        ),
    ]
