# Generated by Django 6.0 on 2026-04-25 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_user_expert_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='scope_dimension',
            field=models.CharField(blank=True, choices=[('COLLEGE', '学院'), ('SCHOOL', '全校')], help_text='管理员角色的数据范围维度。非管理员角色留空。', max_length=50, null=True, verbose_name='数据范围维度'),
        ),
    ]
