# Generated by Codex on 2026-04-25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AsyncTaskRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("IMPORT", "数据导入"),
                            ("EXPORT", "数据导出"),
                            ("REPORT", "报表生成"),
                        ],
                        default="IMPORT",
                        max_length=20,
                        verbose_name="任务类型",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="任务标题")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待执行"),
                            ("RUNNING", "执行中"),
                            ("SUCCESS", "成功"),
                            ("FAILED", "失败"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="任务状态",
                    ),
                ),
                ("progress", models.PositiveSmallIntegerField(default=0, verbose_name="进度")),
                ("message", models.CharField(blank=True, max_length=255, verbose_name="任务消息")),
                ("payload", models.JSONField(blank=True, default=dict, verbose_name="任务参数")),
                ("result", models.JSONField(blank=True, default=dict, verbose_name="任务结果")),
                (
                    "result_file",
                    models.FileField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to="task_results/",
                        verbose_name="结果文件",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="开始时间")),
                ("completed_at", models.DateTimeField(blank=True, null=True, verbose_name="完成时间")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_async_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "异步任务",
                "verbose_name_plural": "异步任务",
                "db_table": "async_task_records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="asynctaskrecord",
            index=models.Index(
                fields=["status", "-created_at"], name="async_task__status_70abac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asynctaskrecord",
            index=models.Index(
                fields=["task_type", "-created_at"], name="async_task__task_ty_48b008_idx"
            ),
        ),
    ]
