# Generated by Django 6.0 on 2026-04-25 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=50, verbose_name='业务模块')),
                ('action', models.CharField(max_length=100, verbose_name='操作动作')),
                ('target_type', models.CharField(blank=True, max_length=50, verbose_name='对象类型')),
                ('target_id', models.CharField(blank=True, max_length=64, verbose_name='对象ID')),
                ('target_name', models.CharField(blank=True, max_length=200, verbose_name='对象名称')),
                ('status', models.CharField(choices=[('SUCCESS', '成功'), ('FAILED', '失败')], default='SUCCESS', max_length=20, verbose_name='操作状态')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='操作详情')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 'operation_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['module', '-created_at'], name='operation_l_module_27c66f_idx'), models.Index(fields=['operator', '-created_at'], name='operation_l_operato_3f48e0_idx'), models.Index(fields=['status', '-created_at'], name='operation_l_status_f112f3_idx')],
            },
        ),
    ]
