# Generated by Codex on 2026-06-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0014_remove_review_review_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expertgroup",
            name="scope",
            field=models.CharField(
                choices=[
                    ("COLLEGE", "院级专家组"),
                    ("SCHOOL", "校级专家组"),
                ],
                default="COLLEGE",
                max_length=20,
                verbose_name="专家组级别",
            ),
        ),
    ]
